Algoritmo "dobro "
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var
// Seção de Declarações das variáveis 
   a,b: inteiro
   m:  real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("informe dois numeros inteiros: ")
   
   leia (a, b)
   
   m <- (a+b)*2
   
   escreval("O dobro de ",a," e ",b," e igual a ",m,".")

Fimalgoritmo